{{- if eq .chezmoi.os "linux" }}
# Fonts
[".fonts/CascadiaCode"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaCode.zip"
    refreshPeriod = "168h"
    exact = true

# Essential CLI tools
[".local/bin/oh-my-posh"]
    type = "file"
    url = "https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
    executable = true
    refreshPeriod = "168h"

[".local/bin/direnv"]
    type = "file"
    url = "https://github.com/direnv/direnv/releases/latest/download/direnv.{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
    executable = true
    refreshPeriod = "168h"

[".local/bin/aws-vault"]
    type = "file"
    url = "https://github.com/99designs/aws-vault/releases/latest/download/aws-vault-{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
    executable = true
    refreshPeriod = "168h"

[".local/bin/aws-nuke"]
    type = "archive-file"
    url = "https://github.com/ekristen/aws-nuke/releases/latest/download/aws-nuke-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
    executable = true
    refreshPeriod = "168h"

# Terraform version manager
[".local/bin/tfenv"]
    type = "archive"
    url = "https://github.com/tfutils/tfenv/archive/refs/heads/master.zip"
    refreshPeriod = "168h"
    stripComponents = 1

# WSL-specific tools
[".local/bin/host-spawn"]
    type = "file"
    url = "https://github.com/1player/host-spawn/releases/latest/download/host-spawn-x86_64"
    executable = true
    refreshPeriod = "168h"

# Modern ls replacement
[".local/bin/eza"]
    type = "archive-file"
    url = "https://github.com/eza-community/eza/releases/latest/download/eza_x86_64-unknown-linux-gnu.tar.gz"
    executable = true
    refreshPeriod = "168h"
    path = "./eza"

# Themes and appearance
[".poshthemes"]
    type = "archive"
    url = "https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/themes.zip"
    refreshPeriod = "168h"
    exact = true

[".themes/Dracula"]
    type = "archive"
    url = "https://github.com/dracula/gtk/archive/master.zip"
    refreshPeriod = "168h"
    stripComponents = 1
    exact = true

[".themes/Sweet-Dark-v40"]
    type = "archive"
    url = "https://github.com/EliverLara/Sweet/releases/latest/download/Sweet-Dark-v40.tar.xz"
    refreshPeriod = "168h"
    stripComponents = 1
    exact = true

# Icons
[".icons/Flatery-Indigo"]
    type = "archive"
    url = "https://github.com/cbrnix/Flatery/archive/refs/tags/Flatery.zip"
    refreshPeriod = "168h"
    stripComponents = 2
    exact = true
    include = ["*/Flatery-Indigo/**"]

[".icons/Flatery-Indigo-Dark"]
    type = "archive"
    url = "https://github.com/cbrnix/Flatery/archive/refs/tags/Flatery.zip"
    refreshPeriod = "168h"
    stripComponents = 2
    exact = true
    include = ["*/Flatery-Indigo-Dark/**"]

[".icons/McMojave-cursors"]
    type = "archive"
    url = "https://github.com/vinceliuice/McMojave-cursors/archive/refs/heads/master.zip"
    refreshPeriod = "168h"
    stripComponents = 2
    exact = true
    include = ["*/dist/**"]

{{- end }}