{{- if eq .chezmoi.os "linux" }}
[".fonts/CascadiaCode"]
  type = "archive"
  url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaCode.zip"
  refreshPeriod = "168h"
  exact = true

[".local/bin/oh-my-posh"]
    type = "file"
    url = "https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
    executable = true
    refreshPeriod = "168h"

[".local/bin/host-spawn"]
    type = "file"
    url = "https://github.com/1player/host-spawn/releases/latest/download/host-spawn-x86_64"
    executable = true
    refreshPeriod = "168h"

[".poshthemes"]
    type = "archive"
    url = "https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/themes.zip"
    refreshPeriod = "168h"
    exact = true

{{- end }}